#!/bin/bash
# Regenerate extension/config.js, sync extension sources into the Xcode
# project, rebuild the macOS app, and reinstall it. This is THE build
# command — on a fresh clone, run this (not xcodebuild/make-app.sh directly:
# config.js is gitignored and generated here, and the Xcode project expects it).
#
# Usage: ./sync-ext.sh [--no-install]
# Token source: $BLINKS_API_TOKEN, or BLINKS_API_TOKEN= line in ../blog/.env
set -euo pipefail
cd "$(dirname "$0")"

BLOG_ENV="${BLOG_ENV:-../blog/.env}"
SERVER="${BLINKS_SERVER:-https://bobbby.online}"

# --- preflight -------------------------------------------------------------
if ! xcode-select -p 2>/dev/null | grep -q "Xcode.app"; then
  echo "error: full Xcode required (not just Command Line Tools)." >&2
  echo "  1. Install Xcode from the App Store" >&2
  echo "  2. sudo xcode-select -s /Applications/Xcode.app" >&2
  echo "  3. sudo xcodebuild -license accept && sudo xcodebuild -runFirstLaunch" >&2
  exit 1
fi

if ! xcodebuild -checkFirstLaunchStatus 2>/dev/null; then
  echo "error: Xcode first-launch setup incomplete. Run:" >&2
  echo "  sudo xcodebuild -license accept && sudo xcodebuild -runFirstLaunch" >&2
  exit 1
fi

# Token: env var wins, otherwise pull from the blog's .env
if [ -z "${BLINKS_API_TOKEN:-}" ]; then
  BLINKS_API_TOKEN=$(grep '^BLINKS_API_TOKEN=' "$BLOG_ENV" 2>/dev/null | cut -d= -f2- || true)
fi
if [ -z "${BLINKS_API_TOKEN:-}" ]; then
  echo "error: no token. Either:" >&2
  echo "  export BLINKS_API_TOKEN=<token>   (same value as the server's)" >&2
  echo "  or have it in $BLOG_ENV" >&2
  exit 1
fi

# --- generate + sync ---------------------------------------------------------
cat > extension/config.js <<EOF
// Generated by sync-ext.sh — do not commit.
const BLINKS_CONFIG = {
  server: "$SERVER",
  token: "$BLINKS_API_TOKEN",
};
EOF
echo "==> wrote extension/config.js (server: $SERVER)"

RES="app/Blinks/Shared (Extension)/Resources"
rsync -a --exclude gen_icons.py --exclude config.example.js extension/ "$RES/"
echo "==> synced extension/ -> $RES"

if [ "${1:-}" = "--no-install" ]; then
  exit 0
fi

# --- build + install ---------------------------------------------------------
echo "==> building macOS app…"
if ! xcodebuild -project app/Blinks/Blinks.xcodeproj -scheme "Blinks (macOS)" \
  -configuration Debug build CODE_SIGN_IDENTITY="-" -quiet; then
  echo "error: build failed. If the error mentions schemes, open" >&2
  echo "  app/Blinks/Blinks.xcodeproj in Xcode once (auto-creates schemes), then re-run." >&2
  exit 1
fi

APP=$(ls -dt "$HOME"/Library/Developer/Xcode/DerivedData/Blinks-*/Build/Products/Debug/Blinks.app | head -1)
rm -rf /Applications/Blinks.app
cp -R "$APP" /Applications/
open /Applications/Blinks.app
echo "==> installed + launched /Applications/Blinks.app"
echo
echo "Safari steps (unsigned dev build):"
echo "  Settings > Advanced > 'Show features for web developers'"
echo "  Settings > Developer > 'Allow unsigned extensions' (re-check after every Safari quit)"
echo "  Settings > Extensions > enable Blinks, allow on All Websites"
echo "  If Blinks isn't listed: quit Safari fully (Cmd-Q) and reopen"
