#!/bin/bash
# Regenerate extension/config.js from the blog's .env, sync extension sources
# into the Xcode project, rebuild the macOS app, and reinstall it.
# Usage: ./sync-ext.sh [--no-install]
set -euo pipefail
cd "$(dirname "$0")"

BLOG_ENV="${BLOG_ENV:-../blog/.env}"
SERVER="${BLINKS_SERVER:-https://bobbby.online}"

# Token: env var wins, otherwise pull from the blog's .env
if [ -z "${BLINKS_API_TOKEN:-}" ]; then
  BLINKS_API_TOKEN=$(grep '^BLINKS_API_TOKEN=' "$BLOG_ENV" | cut -d= -f2-)
fi
if [ -z "$BLINKS_API_TOKEN" ]; then
  echo "error: BLINKS_API_TOKEN not set and not found in $BLOG_ENV" >&2
  exit 1
fi

cat > extension/config.js <<EOF
// Generated by sync-ext.sh — do not commit.
const BLINKS_CONFIG = {
  server: "$SERVER",
  token: "$BLINKS_API_TOKEN",
};
EOF
echo "==> wrote extension/config.js (server: $SERVER)"

RES="app/Blinks/Shared (Extension)/Resources"
rsync -a --exclude gen_icons.py --exclude config.example.js extension/ "$RES/"
echo "==> synced extension/ -> $RES"

if [ "${1:-}" = "--no-install" ]; then
  exit 0
fi

echo "==> building macOS app…"
xcodebuild -project app/Blinks/Blinks.xcodeproj -scheme "Blinks (macOS)" \
  -configuration Debug build CODE_SIGN_IDENTITY="-" -quiet

APP=$(ls -d "$HOME"/Library/Developer/Xcode/DerivedData/Blinks-*/Build/Products/Debug/Blinks.app | head -1)
rm -rf /Applications/Blinks.app
cp -R "$APP" /Applications/
open /Applications/Blinks.app
echo "==> installed + launched /Applications/Blinks.app"
echo "    (quit + reopen Safari, re-check 'Allow unsigned extensions' if needed)"
