const api = typeof browser !== "undefined" ? browser : chrome;

const els = {
  title: document.getElementById("page-title"),
  url: document.getElementById("page-url"),
  input: document.getElementById("tag-input"),
  desc: document.getElementById("desc-input"),
  selected: document.getElementById("selected-tags"),
  list: document.getElementById("tag-list"),
  save: document.getElementById("save-btn"),
  archive: document.getElementById("archive-btn"),
  status: document.getElementById("status"),
  mainView: document.getElementById("main-view"),
  settingsView: document.getElementById("settings-view"),
  settingsBtn: document.getElementById("settings-btn"),
  serverInput: document.getElementById("server-input"),
  tokenInput: document.getElementById("token-input"),
  settingsSave: document.getElementById("settings-save-btn"),
};

// Baked-in defaults from config.js (generated by sync-ext.sh, not committed).
// Anything set via the gear panel overrides these.
const config = typeof BLINKS_CONFIG !== "undefined" ? BLINKS_CONFIG : {};

const state = {
  tab: null,
  settings: {
    server: config.server || "https://bobbby.online",
    token: config.token || "",
  },
  allTags: [], // [{name, count}]
  selectedTags: new Set(),
};

function setStatus(msg, cls) {
  els.status.textContent = msg || "";
  els.status.className = "status" + (cls ? " " + cls : "");
}

async function loadSettings() {
  const stored = await api.storage.local.get(["server", "token", "cachedTags"]);
  if (stored.server) state.settings.server = stored.server;
  if (stored.token) state.settings.token = stored.token;
  if (Array.isArray(stored.cachedTags)) state.allTags = stored.cachedTags;
}

function apiUrl(path) {
  return state.settings.server.replace(/\/+$/, "") + path;
}

function headers() {
  return {
    "Content-Type": "application/json",
    "x-blinks-token": state.settings.token,
  };
}

async function refreshTags() {
  try {
    const res = await fetch(apiUrl("/api/blinks/tags"), { headers: headers() });
    if (!res.ok) throw new Error("HTTP " + res.status);
    const data = await res.json();
    state.allTags = data.tags || [];
    api.storage.local.set({ cachedTags: state.allTags });
    renderTags();
  } catch (e) {
    if (!state.settings.token) {
      setStatus("Set your server + token in settings (gear).", "err");
    } else {
      setStatus("Couldn't load tags: " + e.message, "err");
    }
  }
}

// Tags typed into the input, split on commas. The last fragment doubles as
// a live filter for the existing-tag list.
function typedTags() {
  return els.input.value
    .split(",")
    .map((t) => t.trim().toLowerCase())
    .filter(Boolean);
}

function currentFilter() {
  const parts = els.input.value.split(",");
  return parts[parts.length - 1].trim().toLowerCase();
}

function renderTags() {
  const filter = currentFilter();

  els.selected.innerHTML = "";
  for (const tag of state.selectedTags) {
    const chip = document.createElement("button");
    chip.className = "chip selected";
    chip.textContent = tag;
    chip.onclick = () => {
      state.selectedTags.delete(tag);
      renderTags();
    };
    els.selected.appendChild(chip);
  }

  els.list.innerHTML = "";
  state.allTags
    .filter((t) => !state.selectedTags.has(t.name))
    .filter((t) => !filter || t.name.includes(filter))
    .slice(0, 30)
    .forEach((t) => {
      const chip = document.createElement("button");
      chip.className = "chip";
      chip.innerHTML = "";
      chip.append(t.name);
      const count = document.createElement("span");
      count.className = "count";
      count.textContent = t.count;
      chip.appendChild(count);
      chip.onclick = () => {
        state.selectedTags.add(t.name);
        // Clear the filter fragment that matched this chip
        const parts = els.input.value.split(",");
        parts.pop();
        els.input.value = parts.length ? parts.join(",") + ", " : "";
        renderTags();
      };
      els.list.appendChild(chip);
    });
}

async function save() {
  const tags = [...state.selectedTags, ...typedTags()];
  els.save.disabled = true;
  setStatus("Saving…");
  try {
    const res = await fetch(apiUrl("/api/blinks"), {
      method: "POST",
      headers: headers(),
      body: JSON.stringify({
        url: state.tab.url,
        title: state.tab.title,
        description: els.desc.value.trim() || null,
        tags,
      }),
    });
    if (!res.ok) throw new Error("HTTP " + res.status);
    setStatus("Saved ✓", "ok");
    refreshTags();
  } catch (e) {
    setStatus("Save failed: " + e.message, "err");
  } finally {
    els.save.disabled = false;
  }
}

function archive() {
  const url = state.tab.url;
  api.tabs.create({ url: "https://web.archive.org/save/" + url, active: false });
  api.tabs.create({ url: "https://archive.ph/?url=" + encodeURIComponent(url), active: false });
  setStatus("Archiving opened in background tabs ✓", "ok");
}

function showSettings(show) {
  els.settingsView.hidden = !show;
  els.mainView.hidden = show;
  if (show) {
    els.serverInput.value = state.settings.server;
    els.tokenInput.value = state.settings.token;
  }
}

async function saveSettings() {
  state.settings.server = els.serverInput.value.trim() || "https://bobbby.online";
  state.settings.token = els.tokenInput.value.trim();
  await api.storage.local.set({
    server: state.settings.server,
    token: state.settings.token,
  });
  showSettings(false);
  setStatus("");
  refreshTags();
}

// If this URL was saved before, preselect its tags, prefill notes, and say so.
async function checkExisting() {
  try {
    const res = await fetch(
      apiUrl("/api/blinks/lookup?url=" + encodeURIComponent(state.tab.url)),
      { headers: headers() }
    );
    if (!res.ok) return;
    const data = await res.json();
    if (!data.blink) return;
    for (const tag of data.blink.tags || []) state.selectedTags.add(tag);
    if (data.blink.description && !els.desc.value) els.desc.value = data.blink.description;
    setStatus("Already saved — saving again updates it.", "ok");
    renderTags();
  } catch (e) {
    // lookup is best-effort; saving still works
  }
}

async function init() {
  await loadSettings();

  const [tab] = await api.tabs.query({ active: true, currentWindow: true });
  state.tab = tab;
  els.title.textContent = tab?.title || "";
  els.url.textContent = tab?.url || "";

  renderTags(); // instant render from cache
  refreshTags(); // then refresh from server
  checkExisting();

  if (!state.settings.token) showSettings(true);

  els.input.addEventListener("input", renderTags);
  els.input.addEventListener("keydown", (e) => {
    if (e.key === "Enter") save();
  });
  els.save.onclick = save;
  els.archive.onclick = archive;
  els.settingsBtn.onclick = () => showSettings(els.settingsView.hidden);
  els.settingsSave.onclick = saveSettings;
}

init();
